blackpk1007/TripProject

- src/main/java/com/trip/project/controller/ChatController.java
- src/main/java/com/trip/project/controller/CommunityController.java
- src/main/java/com/trip/project/controller/MainController.java
- src/main/java/com/trip/project/controller/MapController.java
- src/main/java/com/trip/project/dto/CommunityDTO.java
- src/main/java/com/trip/project/dto/LoginDTO.java
- src/main/java/com/trip/project/dto/MapDTO.java
- src/main/java/com/trip/project/mapper/CommunityMapper.java
- src/main/java/com/trip/project/mapper/LoginMapper.java
- src/main/java/com/trip/project/mapper/MapMapper.java
- src/main/java/com/trip/project/service/CommunityService.java
- src/main/java/com/trip/project/service/CommunityServiceImpl.java
- src/main/java/com/trip/project/service/LoginService.java
- src/main/java/com/trip/project/service/LoginServiceImpl.java
- src/main/java/com/trip/project/service/MapService.java
- src/main/java/com/trip/project/service/MapServiceImpl.java
> Controller, DTO, Mapper add

- src/main/resources/templates/main.html
> main page add

- src/main/java/com/trip/project/dto/CommunityDTO.java
- src/main/java/com/trip/project/dto/LoginDTO.java
- src/main/java/com/trip/project/dto/PlaceDTO.java
- src/main/resources/static/tripsql.txt
DTO lombok 설정, sql table 생성 쿼리 파일 추가
> DTO lombok add, sql add

- src/main/java/com/trip/project/controller/CommunityController.java
- src/main/java/com/trip/project/mapper/CommunityMapper.java
- src/main/java/com/trip/project/service/CommunityService.java
- src/main/java/com/trip/project/service/CommunityServiceImpl.java
- src/main/resources/templates/communitydetail.html
- src/main/resources/templates/communitymain.html
- src/main/resources/templates/communityupdateform.html
- src/main/resources/templates/communitywriteform.html
집에서 했던 커뮤니티 기능(컨트롤러, 서비스, mapper), html 추가하였습니다
> 커뮤니티 기능 및 html

- src/main/java/com/trip/project/controller/CommunityController.java
- src/main/java/com/trip/project/mapper/CommunityMapper.java
- src/main/resources/templates/communitymain.html
- src/main/resources/templates/communitywriteform.html
- src/main/resources/templates/main.html
커뮤니티 메인 화면 list 값이 나올 수 있게 수정, 글 작성 화면 값이 넘어 갈 수 있도록 수정, 컨트롤러와 mapper 오타 수정 하였습니다. (홈페이지 메인 화면의 커뮤니티 버튼이 클릭 되지 않아 로그인 버튼에 커뮤니티 링크를 임시 작성 해 놓았습니다. 나중에 수정 해야 합니다.)
> 커뮤니티 수정 사항

- pom.xml
- src/main/java/com/trip/project/TripApplication.java
- src/main/java/com/trip/project/crawling/Crawling.java
- src/main/java/com/trip/project/dto/PlaceDTO.java
- src/main/java/com/trip/project/mapper/MapMapper.java
- src/main/java/com/trip/project/mapper/PlaceMapper.java
- src/main/java/com/trip/project/service/CrawlingService.java
- src/main/java/com/trip/project/service/CrawlingServiceImpl.java
- src/main/resources/static/tripsql.txt
> crawling end

- src/main/java/com/trip/project/controller/LoginController.java
- src/main/java/com/trip/project/controller/UserController.java
- src/main/java/com/trip/project/mapper/LoginMapper.java
- src/main/java/com/trip/project/service/LoginService.java
- src/main/java/com/trip/project/service/LoginServiceImpl.java
> update, delete

- src/main/java/com/trip/project/controller/MapController.java
- src/main/java/com/trip/project/controller/PlanController.java
- src/main/java/com/trip/project/dto/PlaceDTO.java
- src/main/java/com/trip/project/mapper/PlaceMapper.java
- src/main/java/com/trip/project/service/MapService.java
- src/main/java/com/trip/project/service/MapServiceImpl.java
- src/main/java/com/trip/project/service/PlanService.java
- src/main/java/com/trip/project/service/PlanServiceImpl.java
- src/main/resources/templates/airplane.html
- src/main/resources/templates/main.html
- src/main/resources/templates/plan.html
> plan 페이지 add

- src/main/java/com/trip/project/controller/AirPlaneController.java
> airplne controller add

- src/main/java/com/trip/project/controller/ApiController.java
- src/main/java/com/trip/project/dto/OcrDTO.java
- src/main/java/com/trip/project/mapper/OcrMapper.java
- src/main/java/com/trip/project/service/Ocr.java
- src/main/java/com/trip/project/service/OcrTest.java
- src/main/java/com/trip/project/service/OcrTestImpl.java
> ocr update

- pom.xml
- src/main/java/com/trip/project/controller/PlanController.java
- src/main/resources/templates/plan.html
클릭이벤트가 일어난 마커의 데이터들을 DB에서 불러와서 왼쪽 메뉴에 출력
아이콘 변경된 마커를 다른 마커 클릭했을때 원래 마커 아이콘으로 되돌리기
> Place data

- src/main/java/com/trip/project/controller/PlanController.java
- src/main/resources/templates/course.html
- src/main/resources/templates/plan.html
> plan popup

- src/main/java/com/trip/project/controller/LoginController.java
- src/main/resources/static/js/register.js
- src/main/resources/templates/idfindform.html
> 정규식, 로그인 등등

- src/main/java/com/trip/project/controller/PlanController.java
- src/main/resources/static/css/plan.css
- src/main/resources/templates/course.html
- src/main/resources/templates/plan.html
> course detail update

- src/main/java/com/trip/project/controller/PlanController.java
- src/main/java/com/trip/project/dto/PlaceDTO.java
- src/main/java/com/trip/project/dto/PlanDTO.java
- src/main/java/com/trip/project/dto/PlanDetailDTO.java
- src/main/java/com/trip/project/mapper/PlaceMapper.java
- src/main/java/com/trip/project/service/PlanService.java
- src/main/java/com/trip/project/service/PlanServiceImpl.java
- src/main/resources/templates/plan.html
> plan db 저장 search 추가

- src/main/java/com/trip/project/controller/LoginController.java
- src/main/java/com/trip/project/controller/PlanController.java
- src/main/java/com/trip/project/dto/placePagination.java
- src/main/java/com/trip/project/mapper/PlaceMapper.java
- src/main/java/com/trip/project/service/PlanService.java
- src/main/java/com/trip/project/service/PlanServiceImpl.java
- src/main/resources/static/css/plan.css
- src/main/resources/templates/course.html
- src/main/resources/templates/plan.html
- src/main/resources/templates/usermain.html
> plan-paging test

- src/main/java/com/trip/project/controller/LoginController.java
- src/main/resources/static/css/idfindform.css
- src/main/resources/static/css/login.css
- src/main/resources/static/css/pwfindform.css
- src/main/resources/templates/communitydetail.html
- src/main/resources/templates/communitymain.html
- src/main/resources/templates/communityupdateform.html
- src/main/resources/templates/communitywriteform.html
- src/main/resources/templates/idfindform.html
- src/main/resources/templates/login.html
- src/main/resources/templates/pwfindform.html
- src/main/resources/templates/pwfixform.html
- src/main/resources/templates/userupdateform.html
로그인, 아이디-비밀번호 찾기, 비밀번호 수정 페이지 css 수정 및 기능 수정
> 로그인, 아이디-비밀번호 찾기, 비밀번호 수정 페이지 css 수정 및 기능 수정

- src/main/java/com/trip/project/controller/PlanController.java
- src/main/java/com/trip/project/mapper/PlaceMapper.java
- src/main/java/com/trip/project/service/PlanService.java
- src/main/java/com/trip/project/service/PlanServiceImpl.java
- src/main/resources/static/css/plan.css
- src/main/resources/templates/plan.html
> paging aadd

- src/main/java/com/trip/project/controller/ReivewController.java
- src/main/java/com/trip/project/mapper/OcrMapper.java
- src/main/java/com/trip/project/service/OcrTest.java
- src/main/java/com/trip/project/service/OcrTestImpl.java
- src/main/resources/templates/plan.html
두번인증될 경우 place테이블의 placeGood update함
> placeGood update

- src/main/java/com/trip/project/controller/CourseController.java
- src/main/java/com/trip/project/mapper/CourseMapper.java
- src/main/java/com/trip/project/service/CourseService.java
- src/main/java/com/trip/project/service/CourseServiceImpl.java
- src/main/resources/templates/recommandcourse.html
> coursepage

- src/main/java/com/trip/project/TripApplication.java
- src/main/resources/static/css/airplane.css
- src/main/resources/templates/airplane.html
- src/main/resources/templates/coursedetail.html
> 항공 정보, 코스 디테일 페이지 기능 및 css 구현

- src/main/java/com/trip/project/controller/LoginController.java
- src/main/resources/templates/usermain.html
- src/main/resources/templates/userupdateform.html
usermain -> prompt(password) -> userupdateform
> prompt 비밀번호 입력받고 수정페이지로
